### ISSUE TITLE
InvalidDataTypeException: The Typeinfo at xxxxx is not valid

### ISSUE THREAD

**Issue by TheAifam5** [astrelsky/Ghidra-Cpp-Class-Analyzer#14]
Log:
```
2020-04-08	01:31:43	ERROR	(TypeInfoFactory) Unknown Exception ghidra.program.model.data.InvalidDataTypeException: The TypeInfo at 02084150 is not valid
			at ghidra.app.cmd.data.rtti.gcc.typeinfo.SiClassTypeInfoModel.getModel(SiClassTypeInfoModel.java:35)
			at ghidra.app.cmd.data.rtti.gcc.factory.TypeInfoFactory.getTypeInfo(TypeInfoFactory.java:108)
			at ghidra.app.cmd.data.rtti.gcc.typeinfo.AbstractSiClassTypeInfoModel.getParentModels(AbstractSiClassTypeInfoModel.java:39)
			at ghidra.app.cmd.data.rtti.gcc.typeinfo.SiClassTypeInfoModel.getParentModels(SiClassTypeInfoModel.java:14)
			at ghidra.app.cmd.data.rtti.gcc.ClassTypeInfoUtils.sortByMostDerived(ClassTypeInfoUtils.java:327)
			at ghidra.app.plugin.prototype.GccRttiAnalyzer.createVtables(GccRttiAnalyzer.java:272)
			at ghidra.app.plugin.prototype.GccRttiAnalyzer.added(GccRttiAnalyzer.java:149)
			at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:190)
			at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
			at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
			at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
			at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
			at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
			at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
			at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
			at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
			at java.base/java.lang.Thread.run(Thread.java:830)
```

At that address:
![image](https://user-images.githubusercontent.com/2192274/78729254-ec227780-7939-11ea-8f51-5e6b5eaaa82e.png)

**Comment by astrelsky** [comment]
One of those 5 xrefs is inheriting the class that should be there. May you check those addresses and see if one is valid and show the data there?

**Comment by TheAifam5** [comment]
All 5 xrefs are pointing to classes defined by CppClassAnalyzer. Field `__base_type` and `super___class_type_info` -> `super_type_info` -> `_vptr` points to the `02084150` in all of those xrefs.

**Comment by astrelsky** [comment]
The way each type_info is identified is by leveraging the fact that each one starts with a _vptr pointing to its vtable. So a __class_type_info instances first member will be a pointer to __class_type_info::vtable, an __si_class_type_info instance's will be __si_class_type_info::vtable, etc. Assuming `std::exception::~exception *` has been optimized away to `__cxa_free_exception *` I think it is safe to assume that this is supposed to be the type_info for a custom exception with the default destructor. If it was a standard exception the typename would start with `St` but I can see it starts with `18`.

Is this a binary which you have the rights to distribute and is not malicious? It would ensure I can easily reproduce this. If not I can hackup some code later tonight if time allows or this weekend with some custom exceptions and see if I can figure out what is going on.

**Comment by TheAifam5** [comment]
I don’t have rights to publish the binary but I can share more info via email.

**Comment by astrelsky** [comment]
> I don’t have rights to publish the binary but I can share more info via email. 
> 
> Contact me on theaifam5@gmail.com

I will contact you later this afternoon.

It appears I have forgotten two important questions. Is this a static or dynamic binary? Also, is the issue present using ghidra 9.1? Knowing whether it is present in 9.1 will help rule out further issues related to the recent demangler changes in ghidra.

**Comment by TheAifam5** [comment]
Its a dynamic binary. I never used 9.1 version so I can’t tell. I‘m using Ghidra from master branch.

**Comment by astrelsky** [comment]
> Its a shared library (.so). I never used 9.1 version so I can’t tell. I‘m using Ghidra from master branch.

Ah. If the library has any external dependencies, such as libstdc++.so, have they been imported into the project and resolved? The analyzer is supposed to open the external library in ghidra, in the background if not already open, read the data it needs and then close it if it was in the background. However, if it was unable to verify a type_info because the library wasn't present in the project the analyzer is supposed to ignore it, keep analyzing and then inform the user when analysis is complete.

**Comment by TheAifam5** [comment]
I never imported dependencies but I will give a try. It does not break the analysis but I see a lot if errors related to this issue.

**Comment by astrelsky** [comment]
> I never imported dependencies but I will give a try. It does not break the analysis but I see a lot if errors related to this issue.

Oh my. I've found my mistake.
https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/blob/2c8427e593777b0c6cd9ad9d75d579502a628fed/src/main/java/ghidra/app/cmd/data/rtti/gcc/TypeInfoUtils.java#L314-L326

I built up the message to inform the user and then did nothing with it. :man_facepalming:

**Comment by astrelsky** [comment]
This should be fixed by 7ab80c279c199a95a38d9474077b62499bc37892. If you encounter anymore problems feel free to reopen this.

If you get any "Transaction has not been started" errors let me know. I think I got them all though. It is best to open and analyze the external libraries first though.

**Comment by TheAifam5** [comment]
The problem still exists. The `libstdc++.so.6` is analyzed with default options + all RTTI options enabled. I also noticed that, even the imports are loaded, they are in "<EXTERNAL>" rather in the specific imports.

![image](https://user-images.githubusercontent.com/2192274/79072058-411a1100-7cdf-11ea-806c-1d44fe741339.png)

![image](https://user-images.githubusercontent.com/2192274/79072062-4a0ae280-7cdf-11ea-8c7d-564d2d8e99ad.png)


```
2020-04-12	16:52:29	INFO	(ProgramManagerPlugin) Opened program in CodeBrowser tool: Game:/libstdc++.so.6
2020-04-12	16:52:29	ERROR	(TypeInfoFactory) Unknown Exception ghidra.program.model.data.InvalidDataTypeException: The TypeInfo at 020af0b0 is not valid
			at ghidra.app.cmd.data.rtti.gcc.typeinfo.ClassTypeInfoModel.getModel(ClassTypeInfoModel.java:35)
			at ghidra.app.cmd.data.rtti.gcc.factory.TypeInfoFactory.getTypeInfo(TypeInfoFactory.java:108)
			at ghidra.app.cmd.data.rtti.gcc.typeinfo.BaseClassTypeInfoModel.getClassModel(BaseClassTypeInfoModel.java:125)
			at ghidra.app.cmd.data.rtti.gcc.typeinfo.VmiClassTypeInfoModel.getVirtualParents(VmiClassTypeInfoModel.java:173)
			at ghidra.app.cmd.data.rtti.gcc.typeinfo.AbstractSiClassTypeInfoModel.getVirtualParents(AbstractSiClassTypeInfoModel.java:88)
			at ghidra.app.cmd.data.rtti.gcc.typeinfo.SiClassTypeInfoModel.getVirtualParents(SiClassTypeInfoModel.java:14)
			at ghidra.app.cmd.data.rtti.gcc.VtableModel.setupVtablePrefixes(VtableModel.java:252)
			at ghidra.app.cmd.data.rtti.gcc.VtableModel.<init>(VtableModel.java:103)
			at ghidra.app.cmd.data.rtti.gcc.VtableModel.<init>(VtableModel.java:71)
			at ghidra.app.cmd.data.rtti.gcc.ClassTypeInfoUtils.getValidVtable(ClassTypeInfoUtils.java:142)
			at ghidra.app.cmd.data.rtti.gcc.ClassTypeInfoUtils.findVtable(ClassTypeInfoUtils.java:105)
			at ghidra.app.cmd.data.rtti.gcc.typeinfo.AbstractClassTypeInfoModel.getVtable(AbstractClassTypeInfoModel.java:77)
			at ghidra.app.cmd.data.rtti.gcc.typeinfo.SiClassTypeInfoModel.getVtable(SiClassTypeInfoModel.java:14)
			at ghidra.app.cmd.data.rtti.gcc.typeinfo.AbstractClassTypeInfoModel.getVtable(AbstractClassTypeInfoModel.java:31)
			at ghidra.app.cmd.data.rtti.ClassTypeInfo.getVtable(ClassTypeInfo.java:68)
			at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.AbstractCppClassAnalyzer.setupVftables(AbstractCppClassAnalyzer.java:136)
			at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.AbstractCppClassAnalyzer.added(AbstractCppClassAnalyzer.java:104)
			at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:190)
			at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
			at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
			at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
			at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
			at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
			at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
			at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
			at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
			at java.base/java.lang.Thread.run(Thread.java:830)
```
